#Set the join location on player join. If not needed, just disable it :)
enableSpawnTeleport: true
spawnLocation:
  world: world
  x: 0.5
  y: 70.0
  z: 0.5
  yaw: 90.0
  pitch: 0.0

#Configuration for specific features to enable or disable:
features:
  links:
    discord:
      enabled: true
      enabled_message: "&fDiscord: &aminemen.club/discord"
      disabled_message: "&cOops. We currently don't have a &4%link%."
    store:
      enabled: true
      enabled_message: "&fStore: &astore.minemen.club"
      disabled_message: "&cOops. We currently don't have a &4%link%."
    tiktok:
      enabled: true
      enabled_message: "&fTikTok: &atiktok.com/@minemen_club"
      disabled_message: "&cOops. We currently don't have a &4%link%."
    twitter:
      enabled: true
      enabled_message: "&fTwitter: &atwitter.com/Minemen_Network"
      disabled_message: "&cOops. We currently don't have a &4%link%."
    website:
      enabled: true
      enabled_message: "&fWebsite: &aminemen.club"
      disabled_message: "&cOops. We currently don't have a &4%link%."
    youtube:
      enabled: true
      enabled_message: "&fYouTube: &ayoutube.com/@minemen_club"
      disabled_message: "&cOops. We currently don't have a &4%link%."